### ISSUE TITLE
Autodocs in production

### ISSUE THREAD

**Issue by literalpie** [literalpie/storybook-framework-qwik#49]
Autodocs support was added in #45 , but the strategy we're using doesn't work in production. #48 fixed it enough to not break production builds, but the documentation still doesn't get added to stories.

I believe this is because we are detecting if a file is a components file based on whether it has a "tsx" extension, but Qwik breaks files up into multiple parts, each of which is a JS file.

**Comment by unitario** [comment]
Maybe disable resumable functions when building for Storybook?

```
DISABLE_RESUMABLES=1 qwik build
```

Not sure what the trade off is if anything. The only thing I can think of is if the components in question behaves differently when resumed and when not.

Like if you develop components in Storybook and then it "doesn't work" when built in Qwik because of some internal thing in how components behave when resumed and when not.

**Comment by literalpie** [comment]
Yeah, that's already kind of a risk because Qwik uses so much server side stuff, but storybook is all client side. I'd rather not stray farther from Qwik default behavior though.
